// platform
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICE = 'GET_DEVICE';
export const GET_DEVICE_LATEST_MEASUREMENTS = 'GET_DEVICE_LATEST_MEASUREMENTS';
export const GET_MEASUREMENT_SERIES = 'GET_MEASUREMENT_SERIES';
export const GET_REALTIME_UPDATES = 'GET_REALTIME_UPDATES';
export const STOP_REALTIME_UPDATES = 'STOP_REALTIME_UPDATES';
export const SEND_DEVICE_OPERATION = 'SEND_DEVICE_OPERATION';

// menu
export const OPEN_MAIN_MENU = 'OPEN_MAIN_MENU';
export const CLOSE_MAIN_MENU = 'CLOSE_MAIN_MENU';
